//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string RegNo { get; set; }
        public string SchoolID { get; set; }
        public string CategoryID { get; set; }
        public string ParentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherNames { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string StateOfOrigin { get; set; }
        public string LGA { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual School School { get; set; }
        public virtual StudentCategory StudentCategory { get; set; }
    }
}
