//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string SubjectID { get; set; }
        public string CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual SubjectCategory SubjectCategory { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
